kibot:
  version: 1

preflight:
  check_zone_fills: true
  run_erc: true
  run_drc: true
  filters:
    - filter: 'Ignore unconnected copper islands'
      error: '22'
      regex:  'Zone Outline'

outputs:
  - name: 'print_sch'
    comment: "Schematic PDF"
    type: pdf_sch_print
    dir: Schematic

  - name: gerbers
    comment: Gerbers
    type: gerber
    layers:
      - Front
      - Back
      - Edge.Cuts
      - F.SilkS
      - B.SilkS
      - F.Mask
      - B.Mask
      - F.Fab
      - F.CrtYd

  - name: drill
    comment: Drill files
    type: excellon
    options:
      map:
        type: pdf
      pth_and_npth_single_file: true
